name: Publish NuGet Package

on:
  push:
    branches:
      - main
    paths:
      - "libraries/SaaS.Utility.Kafka/**"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore libraries/SaaS.Utility.Kafka/SaaS.Utility.Kafka.csproj

      - name: Build
        run: dotnet build libraries/SaaS.Utility.Kafka/SaaS.Utility.Kafka.csproj --configuration Release --no-restore

      - name: Pack
        run: dotnet pack libraries/SaaS.Utility.Kafka/SaaS.Utility.Kafka.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source "https://nuget.pkg.github.com/GalloFrancesco04/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
